version: 2
updates:
  # Monitor GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Monitor Helm dependencies
  - package-ecosystem: "helm"
    directory: "/charts/common"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/charts/grounds-api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/charts/cockpit"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/charts/grounds-service"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/charts/agones-fleet"
    schedule:
      interval: "weekly"
