{{- if .Values.cockpit.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-http-service
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: cockpit
    {{- with .Values.global.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.global.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cockpit
{{- end }}
