{{- if .Values.admin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-admin-http-service
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
    {{- with .Values.global.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.global.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 3002
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: admin
{{- end }}

