apiVersion: v2
name: grounds-api
description: A Helm chart for grounds-api with player and server services
type: application
version: 0.1.1
appVersion: "0.1.0"
dependencies:
  - name: common
    version: "0.2.0"
    repository: "oci://ghcr.io/groundsgg/charts"
